# Generated by Django 3.1.7 on 2021-05-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20, null='')),
                ('email', models.CharField(default='', max_length=20, null='')),
                ('url', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
