# Generated by Django 3.1.7 on 2021-05-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210506_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.CharField(default=False, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
